package me.zavdav.zcore.exception

internal class UserNotFoundException(val name: String) : RuntimeException()